export const customColours = {
    backgroundColor: "#ededed",
    darkBlue: "#041e42",
    harshBlue: "#0066b0",
    grey: "#9a9a9a",
    lightGrey: "#ddd",
    foreground: "#242424",
    lightBlue: "#e5f4ff",
    componentTitleBar: "#e5eff7",
    highlightGold: "#daaa00",
    white: "#ffffff",
    contentBackground: "#ffffff",
    blockquoteBackground: '#f6f6f6',
    blockquoteForeground: '#6f6f6f',
    blockquoteBorder: '#aaa',
}